name: Build Kodi Repo

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # 👈 ТОВА Е ВАЖНО

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run build script
        run: python tools/build.py

      - name: Commit generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add addons.xml addons.xml.md5 zips/
          git commit -m "Auto build repo" || echo "No changes"
          git push
